headhunter/headhunter/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls')),
    path('', RedirectView.as_view(url='/main/', permanent=True)),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

headhunter/main/urls.py
from django.contrib.flatpages import views as flat_views
from django.urls import path
from django.views.decorators.cache import cache_page

from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('about/', flat_views.flatpage, {'url': '/about/'}, name='about'),
    path('contact/', flat_views.flatpage,
         {'url': '/contact/'}, name='contact'),

    path('applicant/', views.ApplicantListView.as_view(), name='applicant'),
    path('applicant/<int:pk>', views.ApplicantDetailView.as_view(),
         name='applicant-detail'),

    path('vacancy/', views.VacancyListView.as_view(), name='vacancy'),
    path('vacancy/<int:pk>', views.VacancyDetailView.as_view(),
         name='vacancy-detail'),
    path('vacancy/add', views.VacancyAddView.as_view(), name='create_vacancy'),
    path('vacancy/<int:pk>/edit',
         views.VacancyUpdateView.as_view(), name='update_vacancy'),

    path('technology/', views.TechnologyListView.as_view(), name='technology'),


    path('profile/<int:pk>',
         views.UserProfileUpdate.as_view(),
         name='profile'),
    path('accounts/register', views.RegisterUser.as_view(), name='register'),
    path('accounts/login', views.LoginUser.as_view(), name='login'),
]

headhunter/main/models.py
from allauth.account.signals import user_signed_up
from django.contrib.auth.models import Group, User
from django.contrib.postgres.fields import ArrayField
from django.core.mail import EmailMultiAlternatives
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse
from sorl.thumbnail import ImageField


# Create your models here.
CURRENCY_CHOICE = (
    ('r', 'RUB'),
    ('e', 'EUR'),
    ('u', 'USD'),
)


class Technology(models.Model):

    name = models.CharField(
        max_length=100, help_text='Enter a technology name')

    def __str__(self):
        return '{0}(id={1})'.format(self.name, self.id)


class Applicant(models.Model):
    """Model for Candidates whose can have 1 or more Summary.
    """

    GENDER_CHOICE = (
        ('m', 'male'),
        ('f', 'female'),
    )

    def skill_default():
        return list('Oracle')

    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    birth_date = models.DateField(null=True, blank=True)
    email = models.EmailField(max_length=50)
    phone = models.CharField(max_length=20)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICE, blank=True)
    # skill = models.ManyToManyField(Technology, help_text="Select a skill for Candidate")
    skill = ArrayField(models.CharField(max_length=200, blank=True, null=True), default=list)
    image = ImageField(upload_to='images', blank=True, null=True)

    def get_absolute_url(self) -> str:
        return reverse('applicant-detail', args=[str(self.id)])

    def __str__(self):
        """Print class in human-readeable format.
        You can add/remove class-fields.

        :return: str
        :rtype: str
        """
        return '{0} {1}'.format(self.first_name, self.last_name)

    def display_skill(self) -> str:
        """Creates a string for the Skill.
        This is required to display genre in Admin.
        """
        return ', '.join([skill.name for skill in self.skill.all()])
    display_skill.short_description = 'Skill'


class SummaryMain(models.Model):
    """Model for Summary. Consists the main information about candidate's experience.
    """

    VISIBILITY_CHOICE = (
        ('v', 'Visible to anyone'),
        ('n', 'Not visible to anyone'),
    )

    applicant = models.ForeignKey(Applicant, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    salary = models.IntegerField()
    currency = models.CharField(
        max_length=1, choices=CURRENCY_CHOICE, default='r')
    visibility_status = models.CharField(
        max_length=1, choices=VISIBILITY_CHOICE, default='v')
    refresh_date = models.DateTimeField(auto_now=True)

    def get_absolute_url(self) -> str:
        return reverse('summary_main', args=[str(self.id)])

    def __str__(self):
        return self.title


class SummaryDetail(models.Model):
    """Model for Summary. Consists the detailed information about candidate's experience.
    """

    MONTH_CHOICE = (
        ('00', ''),
        ('01', 'January'),
        ('02', 'Febraury'),
        ('03', 'March'),
        ('04', 'April'),
        ('05', 'May'),
        ('06', 'June'),
        ('07', 'July'),
        ('08', 'August'),
        ('09', 'September'),
        ('10', 'October'),
        ('11', 'November'),
        ('12', 'December'),
    )

    summary = models.ForeignKey(SummaryMain, on_delete=models.CASCADE)
    company_name = models.CharField(max_length=50)
    job_title = models.CharField(max_length=20)
    year_begin = models.CharField(max_length=4)
    month_begin = models.CharField(
        max_length=2, choices=MONTH_CHOICE, default='00')
    year_end = models.CharField(max_length=4)
    month_end = models.CharField(
        max_length=2, choices=MONTH_CHOICE, default='00')
    job_duty = models.TextField(max_length=500)

    def get_absolute_url(self) -> str:
        return reverse('summary_detail', args=[str(self.id)])

    def __str__(self):
        return '{0}, {1} ({2}.{3})'.format(self.company_name,
                                           self.job_title,
                                           self.year_begin,
                                           self.month_begin)


class Employer(models.Model):
    """Model for Employees. Consists the main information about company.
    """

    company_name = models.CharField(max_length=50)
    description = models.TextField(max_length=500)
    site = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    update_date = models.DateTimeField(auto_now=True)

    def get_absolute_url(self) -> str:
        return reverse('employer', args=[str(self.id)])

    def __str__(self):
        return f'{self.company_name} ({self.site})'


class Vacancy(models.Model):
    """Model for Vacancy. Consists the main information about vacancy from Employer (Company).
    """

    company_name = models.ForeignKey(Employer, on_delete=models.CASCADE)
    vacancy_name = models.CharField(max_length=50)
    vacancy_description = models.TextField(max_length=200)
    key_skill = models.ManyToManyField(
        Technology, help_text='Select requiement(s) for vacancy')
    salary_min = models.IntegerField(blank=True, null=True)
    salary_max = models.IntegerField(blank=True, null=True)
    currency = models.CharField(
        max_length=1, choices=CURRENCY_CHOICE, default='r')
    publish_date = models.DateField(auto_now=True)
    is_active = models.BooleanField(default=True)

    def get_absolute_url(self) -> str:
        return reverse('vacancy-detail', args=[str(self.id)])

    def __str__(self):
        return f'{self.vacancy_name} ({self.salary_min} - {self.salary_max})'

    def display_key_skill(self) -> str:
        """Creates a string for the Skill.
        This is required to display genre in Admin.
        """
        return ', '.join([skill.name for skill in self.key_skill.all()])
    display_key_skill.short_description = 'Skill'


class Profile(models.Model):
    """Model for user profile. Has connection with User-model.
    """

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    date_of_birth = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.user.username


class Subscriber(models.Model):
    """Model for Subscriber. Class contains users for sending emails with news.
    """

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return f'{self.user.username}({self.user.email})'


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created: bool, **kwargs) -> None:
    """If user profile created, it is auto-add into `common_users` group.
    """
    if created:
        group = Group.objects.get_or_create(name='common_users')
        instance.groups.add(group[0])


@receiver(user_signed_up)
def user_signed_up_(sender, request, user, **kwargs) -> None:
    """Sending `Welcome email` after user sing-up into system.
    """
    subject, from_email, to = 'Welcome', 'admin@mysite', user.email
    text_content = "some custom text or html"
    html_content = ''
    msg = EmailMultiAlternatives(
        subject, text_content, from_email, [to])
    msg.attach_alternative(html_content, "text/html")
    msg.send()


@receiver(post_save, sender=Vacancy)
def send_mail(sender, instance, created: bool, **kwargs) -> None:
    """Sending for all Subscribers `fresh` vacancy list.
    """
    if created:
        email_list = [s.user.email for s in Subscriber.objects.all()]
        subject = f'new vacancy created {instance.vacancy_name}'
        from_email = 'admin@mysite'
        text_content = 'Vacancy {0}, from company {1}'.format(
            instance.vacancy_name, instance.company_name)
        html_content = 'For more details go to <a href="{0}">link</a>.'.format(
            instance.get_absolute_url())
        msg = EmailMultiAlternatives(
            subject, text_content, from_email, email_list)
        msg.attach_alternative(html_content, "text/html")
        msg.send()


class SMSLog(models.Model):
    """Store sended sms-codes.
    """

    phone_number = models.CharField(max_length=15)
    code = models.CharField(max_length=4, null=True, blank=True)
    server_response = models.TextField(max_length=200)


class VacancyView(models.Model):
    """ View for Vacancy, with full information about it.
    """

    company_name = models.CharField(max_length=50)
    site = models.CharField(max_length=100)
    vacancy_name = models.CharField(max_length=50)
    vacancy_description = models.TextField(max_length=200)
    salary_min = models.IntegerField(blank=True, null=True)
    salary_max = models.IntegerField(blank=True, null=True)
    currency = models.CharField(
        max_length=1, choices=CURRENCY_CHOICE, default='r')
    publish_date = models.DateField(auto_now=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        managed = False
        db_table = 'vacancy_employer_view'

headhunter/main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms.models import inlineformset_factory

from main.models import (
    Profile,
    Vacancy,
)


class ProfileForm(forms.ModelForm):
    user = forms.CharField(widget=forms.HiddenInput())

    class Meta:
        model = Profile
        fields = ('date_of_birth', 'user')


class UserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email',)


ProfileFormSet = inlineformset_factory(User, Profile, fields=(
    'date_of_birth',), extra=0, min_num=1, can_delete=False)


class VacancyAddForm(forms.ModelForm):

    class Meta:
        model = Vacancy
        fields = ['company_name', 'vacancy_name', 'vacancy_description',
                  'key_skill', 'salary_min', 'salary_max', 'currency']


class VacancyUpdateForm(forms.ModelForm):

    class Meta:
        model = Vacancy
        fields = ['company_name', 'vacancy_name', 'vacancy_description',
                  'key_skill', 'salary_min', 'salary_max', 'currency']


class CreateNewUser(UserCreationForm):

    username = forms.CharField(
        label='Login', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(
        label='Password1', widget=forms.PasswordInput(
            attrs={'class': 'form-input'}))
    password2 = forms.CharField(label='Password2',
                                widget=forms.PasswordInput(
                                    attrs={'class': 'form-input'}))
    email = forms.EmailField(
        label='Email', widget=forms.TextInput(attrs={'class': 'form-input'}))

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', 'email')

headhunter/main/templates/main/applicant_detail.html
{% extends 'base.html' %}
{% load thumbnail %}


{% block content %}
  <h1>Candidate: {{ applicant.last_name }}, {{ applicant.first_name }}</h1>
  {% thumbnail applicant.image "100x100" crop="center" as im %}
    <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
  {% endthumbnail %}  

  <p>{{ applicant.birth_date }}</p>

  <div style="margin-left: 20px; margin-top: 20px">
    <h4>Detail information:</h4>

    {% for copy in applicant.summarymain_set.all %}
    <hr />
    <p><a href="{% url 'applicant-detail' % }}">{{ copy.title }}</a></p>
    <p>{{ copy.salary }} ({{ copy.get_currency_display }})</p>
    {% endfor %}
  </div>
{% endblock content %}

headhunter/main/templates/main/applicant_list.html
{% extends 'base.html' %}

{% block content %}
<h1>Candidates:</h1>
{% if applicant_list %}
<table class="candidate_list">
  <tr class="first-table-row">
    <th>Name</th>
    <th>Skills</th>
  </tr>

  {% for applicant in applicant_list %}

  <tr>
    <td>
      <a href="{{ applicant.get_absolute_url }}">{{ applicant.last_name }} , {{ applicant.first_name }}
        ({{ applicant.birth_date }})
      </a>
    </td>
    <td>
      {% for skill in applicant.skill.all %}
      <a href="{% url 'applicant' %}?tag={{ skill.id }}">
        {{ skill.name }}
      </a>
      {% endfor %}
    </td>
  </tr>

  {% endfor %}

</table>
{% else %}
<p>There are no applicant in the DB.</p>
{% endif %}
{% endblock %}

headhunter/main/templates/main/login.html
{% extends 'base.html' %}
{% load socialaccount %}
{% providers_media_js %}

{% block content %}
    <h1>Login Form</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="d-grid gap-2 col-6 mx-auto">
            <input class="btn btn-primary" type="submit" value="Login">
            <button class="btn btn-outline-danger" ><a href="{% provider_login_url 'google' %}">Use Google</a></button>
        </div>
    </form>
{% endblock %}

headhunter/main/templates/main/register.html
{% extends 'base.html' %}
{% load socialaccount %}
{% providers_media_js %}

{% block content %}
<h1>New User registration form</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="d-grid gap-2 col-6 mx-auto">
      <input class="btn btn-primary" type="submit" value="Create User">
      <button class="btn btn-outline-danger" ><a href="{% provider_login_url 'google' %}">Use Google</a></button>
    </div>
</form>
{% endblock %}

headhunter/main/templates/main/technology_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Technology:</h1>
{% if technology_list %}
<ul>
    {% for technology in technology_list %}
    <li> {{ technology }}
    </li>
    {% endfor %}
</ul>
{% else %}
<p>There are no technology in the DB.</p>
{% endif %}
{% endblock %}

headhunter/main/templates/main/vacancy_detail.html
{% extends 'base.html' %}
{% load cache %}

{% block content %}
<h1>Vacancy: {{ vacancy.vacancy_name }} ({{ vacancy.company_name }})</h1>

<p>{{ applicant.birth_date }}</p>

<div style="margin-left: 20px; margin-top: 20px">
  <h4>Detail information:</h4>

  {{ vacancy.vacancy_description }}

  {% for skill in vacancy.technology_set.all %}
  <hr />
  <p>{{ skill.name }}</p>
  {% endfor %}
  
  {% cache 60 viewed %}
    <p>viewed {{ num_visits }} time{% if num_visits > 1 %}s{% endif %}.</p>
  {% endcache %}
</div>
{% endblock content %}

headhunter/main/templates/main/vacancy_form.html
{% extends 'base.html'%}
{% load static %}

{% block content %}
<br>
<div class="row">
    <div class="col-md-6">
        <div class="card card-body">
            <form action="" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <hr>
                <input type="submit" class="btn btn-primary" name="Submit">
            </form>
        </div>
    </div>
</div>

{% endblock %}

headhunter/main/templates/main/vacancy_form_update.html
{% extends 'base.html'%}
{% load static %}

{% block content %}
<br>
<div class="row">
    <div class="col-md-6">
        <div class="card card-body">
            <form action="" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <hr>
                <input type="submit" class="btn btn-primary" name="Submit">
            </form>
        </div>
    </div>
</div>

{% endblock %}

headhunter/main/templates/main/vacancy_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Vacancy List:</h1>
{% if vacancy_list %}
<ul>
    {% for vacancy in vacancy_list %}
    <li>
        <a href="{{ vacancy.get_absolute_url }}">{{ vacancy }}</a>
    </li>
    {% endfor %}
</ul>
{% else %}
<p>There are no vacancy in the DB.</p>
{% endif %}
{% endblock %}